FROM openjdk:11

RUN mkdir /vertx

COPY target/vertx-todo.jar /vertx/vertx-todo.jar
COPY src/main/resources/config.yaml /vertx/config.yaml

WORKDIR /vertx

ENTRYPOINT [ "sh", "-c" ]

CMD ["java -jar vertx-todo.jar"]